
### Get All Patients
GET http://localhost:8082/patient/all 


### Get a product by id
GET http://localhost:8082/patient/1


### Add a product
POST  http://localhost:8082/patient/add HTTP/1.1
content-type: application/json

{
    "id":5,
    "name": "Alamin khan",
    "age": 23,
    "gender": "male",
    "address": "Raatusee 23",
    "mobile":12345
}

### Update a product
PUT   http://localhost:8082/update/5 HTTP/1.1
content-type: application/json

{
    "id":5,
    "name": "Mohammad Alamin khan",
    "age": 23,
    "gender": "male",
    "address": "Raatusee 23",
    "mobile":12345
}

### Delete a product
DELETE http://localhost:8082/patient/delete/4


